from django.contrib.auth.decorators import login_required
from django.urls import path

from .utils import calculate_distance_view
from .views import (
    AboutView,
    AdminRegisterView,
    AdoptionApplyView,
    ApplicationConfirmationView,
    ContactView,
    HomeView,
    LoginView,
    MapView,
    PetCreateView,
    PetDeleteView,
    PetListView,
    PetUpdateView,
    RegisterView,
    cancel_application,
    change_password,
    initKhalti,
    landing_page,
    logout_view,
    my_applications,
    nearby_pets,
    pay_application,
    pet_detail,
    pet_search,
    recommend_pets,
    review_application,
    save_location,
    shelter_applications,
    shelter_dashboard,
    shelter_pets,
    verifyKhalti,
    verify_payment,
)

urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('index/', HomeView.as_view(), name='index'),
    path('pets/', PetListView.as_view(), name='pet_list'),
    path('pet/<int:pet_id>/', pet_detail, name='pet_detail'),
    path('search/', pet_search, name='pet_search'),
    path('recommend/', recommend_pets, name='recommend_pets'),
    path('nearby/', nearby_pets, name='nearby_pets'),
    path('save-location/', save_location, name='save_location'),
    path('calculate-distance/', calculate_distance_view, name='calculate_distance'),
    path('apply/', AdoptionApplyView.as_view(), name='apply'),
    path('my-applications/', login_required(my_applications), name='my_applications'),
    path('applications/<int:app_id>/cancel/', login_required(cancel_application), name='cancel_application'),
    path('applications/<int:app_id>/pay/', login_required(pay_application), name='pay_application'),
    path('applications/confirmation/<int:application_id>/', ApplicationConfirmationView.as_view(), name='application_confirmation'),
    path('init-khalti/', initKhalti, name='initkhalti'),
    path('verify-khalti/', verifyKhalti, name='verifykhalti'),
    path('verify-payment/', verify_payment, name='verify_payment'),
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('register/admin/', AdminRegisterView.as_view(), name='register_admin'),
    path('logout/', logout_view, name='logout'),
    path('about/', AboutView.as_view(), name='about'),
    path('map/', MapView.as_view(), name='map'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('shelter/', login_required(shelter_dashboard), name='shelter_dashboard'),
    path('shelter/pets/', login_required(shelter_pets), name='shelter_pets'),
    path('shelter/pets/add/', PetCreateView.as_view(), name='pet_create'),
    path('shelter/pets/<int:pk>/edit/', PetUpdateView.as_view(), name='pet_edit'),
    path('shelter/pets/<int:pk>/delete/', PetDeleteView.as_view(), name='pet_delete'),
    path('shelter/applications/', login_required(shelter_applications), name='shelter_applications'),
    path('shelter/applications/<int:app_id>/', login_required(review_application), name='review_application'),
    path('shelter/change-password/', login_required(change_password), name='change_password'),
]
